apiVersion: apps/v1
kind: Deployment
metadata:
  name: banchiospring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banchiospring-app
  template:
    metadata:
      labels:
        app: banchiospring-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: banchiospring-app
        image: banchioacrprem.azurecr.io/com.banchio.restapi:latest
        env: 
        - name: AZURE_CLIENT_ID
          valueFrom: 
            secretKeyRef: 
              name: banchiospring-app-sp
              key: clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom: 
            secretKeyRef: 
              name: banchiospring-app-sp
              key: secret
        - name: AZURE_TENANT_ID
          valueFrom: 
            secretKeyRef: 
              name: banchiospring-app-sp
              key: tenantid
        resources:
          requests:
            cpu: "100m"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: banchiospring-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: banchiospring-app